project:
  type: book

book:
  # title: "Intensivo em tidyverse"
  author: "Marcel Ferreira"
  date: today
  chapters:
    - index.qmd
    - intro.qmd
    - basics.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    df-print: paged
  pdf:
    documentclass: scrreprt

editor: visual

